2021-01-14 13:01:56 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 314, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 546, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'invalid HTTP method'"
2021-01-14 13:01:57 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 314, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 546, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'invalid HTTP method'"
2021-01-14 13:01:57 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 314, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 546, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'invalid HTTP method'"
2021-01-14 13:01:57 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 314, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 546, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'invalid HTTP method'"
2021-01-14 13:01:57 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 314, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 546, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'invalid HTTP method'"
2021-01-14 13:01:57 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 314, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 546, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'invalid HTTP method'"
2021-01-14 13:04:14 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook 529fb8fb2bb3bcd29fbc4a0e3a3258363490196d501f345808c7be1c20a1f6d1 from 192.168.86.192
2021-01-14 13:05:16 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook 529fb8fb2bb3bcd29fbc4a0e3a3258363490196d501f345808c7be1c20a1f6d1 from 192.168.86.192
2021-01-14 13:05:16 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook 529fb8fb2bb3bcd29fbc4a0e3a3258363490196d501f345808c7be1c20a1f6d1 from 192.168.86.192
2021-01-14 13:05:17 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook 529fb8fb2bb3bcd29fbc4a0e3a3258363490196d501f345808c7be1c20a1f6d1 from 192.168.86.192
2021-01-14 13:05:17 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook 529fb8fb2bb3bcd29fbc4a0e3a3258363490196d501f345808c7be1c20a1f6d1 from 192.168.86.192
2021-01-14 13:05:31 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook 529fb8fb2bb3bcd29fbc4a0e3a3258363490196d501f345808c7be1c20a1f6d1 from 192.168.86.192
2021-01-14 13:06:03 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook 529fb8fb2bb3bcd29fbc4a0e3a3258363490196d501f345808c7be1c20a1f6d1 from 192.168.86.192
2021-01-14 13:08:04 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook 529fb8fb2bb3bcd29fbc4a0e3a3258363490196d501f345808c7be1c20a1f6d1 from 192.168.86.192
2021-01-14 13:09:51 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook 529fb8fb2bb3bcd29fbc4a0e3a3258363490196d501f345808c7be1c20a1f6d1 from 192.168.86.192
2021-01-14 13:10:53 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook 529fb8fb2bb3bcd29fbc4a0e3a3258363490196d501f345808c7be1c20a1f6d1 from 192.168.86.192
2021-01-14 13:10:53 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook 529fb8fb2bb3bcd29fbc4a0e3a3258363490196d501f345808c7be1c20a1f6d1 from 192.168.86.192
2021-01-14 13:11:57 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook 529fb8fb2bb3bcd29fbc4a0e3a3258363490196d501f345808c7be1c20a1f6d1 from 192.168.86.192
2021-01-14 13:13:57 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook 529fb8fb2bb3bcd29fbc4a0e3a3258363490196d501f345808c7be1c20a1f6d1 from 192.168.86.192
2021-01-14 13:29:19 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook 529fb8fb2bb3bcd29fbc4a0e3a3258363490196d501f345808c7be1c20a1f6d1 from 192.168.86.192
2021-01-14 13:45:02 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook 529fb8fb2bb3bcd29fbc4a0e3a3258363490196d501f345808c7be1c20a1f6d1 from 192.168.86.192
